const nodemailer = require("nodemailer");

export default async function POST(req, res) {
    try {
        const { name,  phone, email, website,  IP, currentdate, pageUrl } = await req.body;
        const brandname = 'Bitswits'
        const transporter = nodemailer.createTransport({
            service: "gmail",
            host: "smtp.gmail.com",
            port: 465,
            secure: true,
            auth: {
                user: 'signups@bitswits.co',
                pass: "JHR*7FMW5PPF9hN@"
            }
        })

        const mailOptions = {
            from: 'signups@bitswits.co',
            to: 'signups@bitswits.co',
            subject: `New Lead Generated By Bitswits`,
            html: `<table>
               
                    <tr>
                        <th>Name</th>
                        <td>${name}</td>
                    </tr>
                   
                    <tr>
                        <th>Phone</th>
                        <td>${phone}</td>
                    </tr>

                    <tr>
                        <th>Email</th>
                        <td>${email}</td>
                    </tr>
                    <tr>
                    <th>Website</th>
                    <td>${website}</td>
                </tr>
                
              
                    <tr>
                    <th>IP</th>
                    <td>${IP}</td>
                </tr>
                <tr>
                    <th>Currentdate</th>
                    <td>${currentdate}</td>
                </tr>
               
                    <tr>
                        <th>pageUrl</th>
                        <td>${pageUrl}</td>
                    </tr>
                    <tr>
                        <th>Brand Name</th>
                        <td>${brandname}</td>
                    </tr>
                    
                    
                
               
            </table>`
        }

        await transporter.sendMail(mailOptions);





        return res.json({ "message": "Email send sucessfully", "data": [name,  phone, email,website,  brandname, IP, currentdate, pageUrl], "status": 200 });
    } catch (error) {
        return res.json({ "message": "Failed to send Email", "data": error, "status": 500 });
    }
}